default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  user: postgres
  password: postgres
  
development:
  <<: *default
  database: jocha
